../font-maker pbfs/NotoSans-Regular \
fonts/Noto-unhinted/NotoSans-Regular.ttf \
fonts/Noto-unhinted/NotoSansArmenian-Regular.ttf \
fonts/Noto-unhinted/NotoSansHebrew-Regular.ttf \
fonts/Noto-unhinted/NotoSansArabic-Regular.ttf \
fonts/Noto-unhinted/NotoSansSyriacEastern-Regular.ttf \
fonts/Noto-unhinted/NotoSansThaana-Regular.ttf \
fonts/Noto-unhinted/NotoSansNKo-Regular.ttf \
fonts/Noto-unhinted/NotoSansSamaritan-Regular.ttf \
fonts/Noto-unhinted/NotoSansMandaic-Regular.ttf \
fonts/Noto-unhinted/NotoSansDevanagari-Regular.ttf \
fonts/Noto-unhinted/NotoSansBengali-Regular.ttf \
fonts/Noto-unhinted/NotoSansGurmukhi-Regular.ttf \
fonts/Noto-unhinted/NotoSansGujarati-Regular.ttf \
fonts/Noto-unhinted/NotoSansOriya-Regular.ttf \
fonts/Noto-unhinted/NotoSansTamil-Regular.ttf \
fonts/Noto-unhinted/NotoSansTelugu-Regular.ttf \
fonts/Noto-unhinted/NotoSansKannada-Regular.ttf \
fonts/Noto-unhinted/NotoSansMalayalam-Regular.ttf \
fonts/Noto-unhinted/NotoSansSinhala-Regular.ttf \
fonts/Noto-unhinted/NotoSansThai-Regular.ttf \
fonts/Noto-unhinted/NotoSansLao-Regular.ttf \
fonts/Noto-unhinted/NotoSansTibetan-Regular.ttf \
fonts/Noto-unhinted/NotoSansMyanmar-Regular.ttf \
fonts/Noto-unhinted/NotoSansGeorgian-Regular.ttf \
fonts/Noto-unhinted/NotoSansEthiopic-Regular.ttf \
fonts/Noto-unhinted/NotoSansCherokee-Regular.ttf \
fonts/Noto-unhinted/NotoSansCanadianAboriginal-Regular.ttf \
fonts/Noto-unhinted/NotoSansOgham-Regular.ttf \
fonts/Noto-unhinted/NotoSansRunic-Regular.ttf \
fonts/Noto-unhinted/NotoSansTagalog-Regular.ttf \
fonts/Noto-unhinted/NotoSansHanunoo-Regular.ttf \
fonts/Noto-unhinted/NotoSansBuhid-Regular.ttf \
fonts/Noto-unhinted/NotoSansTagbanwa-Regular.ttf \
fonts/Noto-unhinted/NotoSansKhmer-Regular.ttf \
fonts/Noto-unhinted/NotoSansMongolian-Regular.ttf \
fonts/Noto-unhinted/NotoSansLimbu-Regular.ttf \
fonts/Noto-unhinted/NotoSansTaiLe-Regular.ttf \
fonts/Noto-unhinted/NotoSansNewTaiLue-Regular.ttf \
fonts/Noto-unhinted/NotoSansBuginese-Regular.ttf \
fonts/Noto-unhinted/NotoSansTaiTham-Regular.ttf \
fonts/Noto-unhinted/NotoSansBalinese-Regular.ttf \
fonts/Noto-unhinted/NotoSansSundanese-Regular.ttf \
fonts/Noto-unhinted/NotoSansBatak-Regular.ttf \
fonts/Noto-unhinted/NotoSansLepcha-Regular.ttf \
fonts/Noto-unhinted/NotoSansOlChiki-Regular.ttf \
fonts/Noto-unhinted/NotoSansSymbols-Regular.ttf \
fonts/Noto-unhinted/NotoSansSymbols2-Regular.ttf \
fonts/Noto-unhinted/NotoSansGlagolitic-Regular.ttf \
fonts/Noto-unhinted/NotoSansCoptic-Regular.ttf \
fonts/Noto-unhinted/NotoSansTifinagh-Regular.ttf \
fonts/Noto-unhinted/NotoSansCJKtc-Regular.otf \
fonts/Noto-unhinted/NotoSansYi-Regular.ttf \
fonts/Noto-unhinted/NotoSansLisu-Regular.ttf \
fonts/Noto-unhinted/NotoSansVai-Regular.ttf \
fonts/Noto-unhinted/NotoSansBamum-Regular.ttf \
fonts/Noto-unhinted/NotoSansSylotiNagri-Regular.ttf \
fonts/Noto-unhinted/NotoSansPhagsPa-Regular.ttf \
fonts/Noto-unhinted/NotoSansSaurashtra-Regular.ttf \
fonts/Noto-unhinted/NotoSansKayahLi-Regular.ttf \
fonts/Noto-unhinted/NotoSansRejang-Regular.ttf \
fonts/Noto-unhinted/NotoSansJavanese-Regular.ttf \
fonts/Noto-unhinted/NotoSansCham-Regular.ttf \
fonts/Noto-unhinted/NotoSansTaiViet-Regular.ttf \
fonts/Noto-unhinted/NotoSansMeeteiMayek-Regular.ttf