ROOT=notofonts.github.io-main/fonts/
PATH=unhinted/ttf

../font-maker --name "Noto Sans Regular" out \
$ROOT/NotoSans/$PATH/NotoSans-Regular.ttf \
$ROOT/NotoSansArmenian/$PATH/NotoSansArmenian-Regular.ttf \
$ROOT/NotoSansHebrew/$PATH/NotoSansHebrew-Regular.ttf \
$ROOT/NotoSansArabic/$PATH/NotoSansArabic-Regular.ttf \
$ROOT/NotoSansSyriac/$PATH/NotoSansSyriac-Regular.ttf \
$ROOT/NotoSansThaana/$PATH/NotoSansThaana-Regular.ttf \
$ROOT/NotoSansNKo/$PATH/NotoSansNKo-Regular.ttf \
$ROOT/NotoSansSamaritan/$PATH/NotoSansSamaritan-Regular.ttf \
$ROOT/NotoSansDevanagari/$PATH/NotoSansDevanagari-Regular.ttf \
$ROOT/NotoSansBengali/$PATH/NotoSansBengali-Regular.ttf \
$ROOT/NotoSansGurmukhi/$PATH/NotoSansGurmukhi-Regular.ttf \
$ROOT/NotoSansGujarati/$PATH/NotoSansGujarati-Regular.ttf \
$ROOT/NotoSansOriya/$PATH/NotoSansOriya-Regular.ttf \
$ROOT/NotoSansTamil/$PATH/NotoSansTamil-Regular.ttf \
$ROOT/NotoSansTelugu/$PATH/NotoSansTelugu-Regular.ttf \
$ROOT/NotoSansKannada/$PATH/NotoSansKannada-Regular.ttf \
$ROOT/NotoSansMalayalam/$PATH/NotoSansMalayalam-Regular.ttf \
$ROOT/NotoSansSinhala/$PATH/NotoSansSinhala-Regular.ttf \
$ROOT/NotoSansThai/$PATH/NotoSansThai-Regular.ttf \
$ROOT/NotoSansLao/$PATH/NotoSansLao-Regular.ttf \
$ROOT/NotoSerifTibetan/$PATH/NotoSerifTibetan-Regular.ttf \
$ROOT/NotoSansMyanmar/$PATH/NotoSansMyanmar-Regular.ttf \
$ROOT/NotoSansGeorgian/$PATH/NotoSansGeorgian-Regular.ttf \
$ROOT/NotoSansEthiopic/$PATH/NotoSansEthiopic-Regular.ttf \
$ROOT/NotoSansCherokee/$PATH/NotoSansCherokee-Regular.ttf \
$ROOT/NotoSansCanadianAboriginal/$PATH/NotoSansCanadianAboriginal-Regular.ttf \
$ROOT/NotoSansOgham/$PATH/NotoSansOgham-Regular.ttf \
$ROOT/NotoSansRunic/$PATH/NotoSansRunic-Regular.ttf \
$ROOT/NotoSansTagalog/$PATH/NotoSansTagalog-Regular.ttf \
$ROOT/NotoSansHanunoo/$PATH/NotoSansHanunoo-Regular.ttf \
$ROOT/NotoSansBuhid/$PATH/NotoSansBuhid-Regular.ttf \
$ROOT/NotoSansTagbanwa/$PATH/NotoSansTagbanwa-Regular.ttf \
$ROOT/NotoSansKhmer/$PATH/NotoSansKhmer-Regular.ttf \
$ROOT/NotoSansMongolian/$PATH/NotoSansMongolian-Regular.ttf \
$ROOT/NotoSansLimbu/$PATH/NotoSansLimbu-Regular.ttf \
$ROOT/NotoSansTaiLe/$PATH/NotoSansTaiLe-Regular.ttf \
$ROOT/NotoSansNewTaiLue/$PATH/NotoSansNewTaiLue-Regular.ttf \
$ROOT/NotoSansBuginese/$PATH/NotoSansBuginese-Regular.ttf \
$ROOT/NotoSansTaiTham/$PATH/NotoSansTaiTham-Regular.ttf \
$ROOT/NotoSansBalinese/$PATH/NotoSansBalinese-Regular.ttf \
$ROOT/NotoSansSundanese/$PATH/NotoSansSundanese-Regular.ttf \
$ROOT/NotoSansBatak/$PATH/NotoSansBatak-Regular.ttf \
$ROOT/NotoSansLepcha/$PATH/NotoSansLepcha-Regular.ttf \
$ROOT/NotoSansOlChiki/$PATH/NotoSansOlChiki-Regular.ttf \
$ROOT/NotoSansSymbols/$PATH/NotoSansSymbols-Regular.ttf \
$ROOT/NotoSansSymbols2/$PATH/NotoSansSymbols2-Regular.ttf \
$ROOT/NotoSansGlagolitic/$PATH/NotoSansGlagolitic-Regular.ttf \
$ROOT/NotoSansCoptic/$PATH/NotoSansCoptic-Regular.ttf \
$ROOT/NotoSansTifinagh/$PATH/NotoSansTifinagh-Regular.ttf \
$ROOT/NotoSansYi/$PATH/NotoSansYi-Regular.ttf \
$ROOT/NotoSansLisu/$PATH/NotoSansLisu-Regular.ttf \
$ROOT/NotoSansVai/$PATH/NotoSansVai-Regular.ttf \
$ROOT/NotoSansBamum/$PATH/NotoSansBamum-Regular.ttf \
$ROOT/NotoSansSylotiNagri/$PATH/NotoSansSylotiNagri-Regular.ttf \
$ROOT/NotoSansPhagsPa/$PATH/NotoSansPhags-Pa-Regular.ttf \
$ROOT/NotoSansSaurashtra/$PATH/NotoSansSaurashtra-Regular.ttf \
$ROOT/NotoSansKayahLi/$PATH/NotoSansKayahLi-Regular.ttf \
$ROOT/NotoSansRejang/$PATH/NotoSansRejang-Regular.ttf \
$ROOT/NotoSansJavanese/$PATH/NotoSansJavanese-Regular.ttf \
$ROOT/NotoSansCham/$PATH/NotoSansCham-Regular.ttf \
$ROOT/NotoSansTaiViet/$PATH/NotoSansTaiViet-Regular.ttf \
$ROOT/NotoSansMeeteiMayek/$PATH/NotoSansMeeteiMayek-Regular.ttf